services:
  mysql:
    image: mysql:latest
    container_name: mysql-be-talent-test-case
    restart: always
    env_file:
      - path: ../.env
        required: false
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
